name: Semgrep SAST



on:

  push:



jobs:

  semgrep:

    name: Run Semgrep SAST

    runs-on: ubuntu-latest



    steps

      - name heckout source code

        uses actions/checkoutv6



      - name et up ython

        uses actions/setup-pythonv6

        with

          python-version '3.x'



      - name nstall emgrep

        run python -m pip install semgrep



      - name un emgrep 

        run semgrep --config=auto .

















